// Angular2 Fundamentals/Gallery-Angular2/bull-gallery/src/app/components/profile/profile.component.ts
import {Component, OnInit} from '@angular/core';
import {Router, RouterModule, RouterLink} from '@angular/router';
import {RemoteService} from "../../services/remote/remote.service";
import {FormBuilder, FormGroup} from "@angular/forms";
import {RegisterModel} from "../../services/models/register.model";
import {ProfileModel} from "../../services/models/profile.model";

@Component({
  selector: 'bull-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss']
})
export class ProfileComponent implements OnInit {
  public username: string;
  public avatar: string;
  public editProfile: FormGroup;
  public model: any;
  public id: string;

  constructor(public remoteService: RemoteService, private router: Router, private fb: FormBuilder,) {
    this.username = localStorage.getItem('username');
    this.model = new ProfileModel((localStorage.getItem('username')), 'user', '');
  }


  ngOnInit() {
    // GET USER DETAILS
    this.remoteService.getUserDetails().subscribe(data => {

        this.avatar = data[0]['avatar'];
        this.id = data[0]['_id']
      },
      err => {
        console.log(err.message);
      });

    this.editProfile = this.fb.group({
      newAvatar: ['']
    })
  }

  // UPDATE USER AVATAR
  update(e) {
    this.model.avatar = e.value.newAvatar;

    this.remoteService.editProfile(this.model, this.id).subscribe(data => {
        window.location.reload();
        this.router.navigate(['/']);
      },
      err => {
        console.log(err.message);
      })

  }


}

<div class="heading">
  <h1>Profile</h1>
  <hr>
</div>

<div class="login-page profile-page">
  <div class="form  profile-form">

    <!--Form-->
    <form  (ngSubmit)="update(editProfile)" [formGroup]="editProfile" class="login-form">
      <div class="login-form">
        <img src={{avatar}} alt="img">
        <label for="avatar">Choose Avatar</label>
        <input formControlName="newAvatar" id="avatar" type="text" placeholder="" value={{avatar}}/>
      </div>

      <div class="login-form">
        <label for="title">Username</label>
        <input id="title" type="text" placeholder="Name" value="{{username}}" disabled/>

        <label for="password">Password</label>
        <input id="password" type="password" placeholder="Name" value="password" disabled/>

        <button type="submit" class="btn btn--default shiny btn-login">Save</button>
      </div>
    </form>
  </div>
</div>

// ReactJS Fundamentals/Bull-Gallery/src/components/non-shared/Profile/Profile.jsx
import React, {Component} from 'react';
import {withRouter} from 'react-router-dom';
import {getUserDetails, editProfile} from "../../../api/remote";
import toastr from 'toastr';


class Profile extends Component {
    constructor(props) {
        super(props);

        this.state = {
            username: '',
            avatar: '',
            id: ''
        };

        this.onChangeHandler = this.onChangeHandler.bind(this);
        this.onSubmitHandler = this.onSubmitHandler.bind(this);
    }

    componentDidMount() {
        this.getData();
    }

    async getData() {

        // GET USER DETAILS
        const res = await getUserDetails();
        if (res.error) {
            toastr.error('Loading unsuccessful');
            return;
        }
        toastr.success('Posts Loaded Successfully');


        this.setState({username: res[0].username, avatar: res[0].avatar, id: res[0]._id,});
        console.log(this.state);
    }

    onChangeHandler(e) {
        this.setState({[e.target.name]: e.target.value});
    }

    async onSubmitHandler(e) {
        e.preventDefault();

        // EDIT AVATAR
        const res = await editProfile(this.state.id, this.state.avatar);
        if(res.error){
            toastr.error('Edit unsuccessful');
            return;
        }

        window.location.reload();
        this.props.history.push('/')
    }

    render() {
        return (
            <div>
                <div className="heading">
                    <h1>Profile</h1>
                    <hr/>
                </div>

                <div className="login-page profile-page">
                    <div className="form  profile-form">

                        <form onSubmit={this.onSubmitHandler} className="login-form">
                            <div className="login-form">
                                <img src={this.state.avatar} alt="img"/>
                                <label htmlFor="avatar">Choose Avatar</label>
                                <input onChange={this.onChangeHandler} id="avatar" name="avatar" type="text"
                                       placeholder=""
                                       value={this.state.avatar}/>
                            </div>

                            <div className="login-form">
                                <label htmlFor="title">Username</label>
                                <input id="title" type="text" placeholder="Name" value={this.state.username} disabled/>

                                <label htmlFor="password">Password</label>
                                <input id="password" type="password" placeholder="Name" value="password" disabled/>

                                <button type="submit" className="btn btn--default shiny btn-login">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        );
    }
}

export default withRouter(Profile)
