// ReactJS Fundamentals/Bull-Gallery/src/components/non-shared/Details/Details.jsx
import React, {Component} from 'react';
import {withRouter} from 'react-router-dom';
import {
    getCommentsOfPost, getPostDetails, postComment, deleteComment, deletePost,
    deleteCommentsOfPost
} from "../../../api/remote";
import toastr from 'toastr';


class Details extends Component {
    constructor(props) {
        super(props);

        this.state = {
            username: '',
            title: '',
            image: '',
            category: '',
            description: '',
            creator: '',
            counter: '',
            lmt: '',
            comments: [],
            commentText: ''
        };

        this.onChangeHandler = this.onChangeHandler.bind(this);
        this.onSubmitHandler = this.onSubmitHandler.bind(this);
        this.calcTime = this.calcTime.bind(this);
        this.deleteCmt = this.deleteCmt.bind(this);
        this.deletePostById = this.deletePostById.bind(this);
    }

    componentDidMount() {
        this.getData();
    }

    async getData() {
        console.log(this.props.match.params.id);

        // GET POST DETAILS
        const res = await getPostDetails(this.props.match.params.id);

        if (res.error) {
            toastr.error('Loading unsuccessful');
            return;
        }

        this.setState({
            title: res.title,
            image: res.image,
            category: res.category,
            description: res.description,
            creator: res.creator,
            counter: res.counter,
            lmt: res._kmd.lmt,
        });
        this.setState({username: localStorage.getItem('username')});

        // GET COMMENTS FOR POST
        const resComments = await getCommentsOfPost(this.props.match.params.id);

        if (resComments.success === false) {
            toastr.error('Loading comments unsuccessful');
            return;
        }

        this.setState({comments: resComments});
        console.log(this.state.comments);

    }

    onChangeHandler(e) {
        this.setState({[e.target.name]: e.target.value});
    }

    async onSubmitHandler(e) {
        e.preventDefault();

        const resComment = await postComment(this.state.username, this.state.commentText, this.props.match.params.id);

        if (resComment.success === false) {
            toastr.error('Commenting unsuccessful');
            return;
        }

        this.refs.form.reset();
        console.log(resComment);

        // LOAD COMMENTS AFTER COMMENTING
        const resComments = await getCommentsOfPost(this.props.match.params.id);

        if (resComments.success === false) {
            toastr.error('Loading unsuccessful');
            return;
        }

        this.setState({comments: resComments});
        console.log(this.state.comments);
    }

    async deleteCmt(id) {
        const resDelete = await deleteComment(id);

        if (resDelete.success) {
            toastr.success('Comment Deleted');
        }

        // REFRESH COMMENTS FOR POST
        const resComments = await getCommentsOfPost(this.props.match.params.id);

        if (resComments.success === false) {
            toastr.error('Loading unsuccessful');
            return;
        }

        this.setState({comments: resComments});
        console.log(this.state.comments);
    }

    async deletePostById(id){
        const resDeletePost = await deletePost(id);
        const resDelete = await deleteCommentsOfPost(id);
        if (resDelete.success === false) {
            toastr.error('Delete failed');
            return;
        }
        this.props.history.push('/');
    }

    calcTime(dateIsoFormat) {

        let diff = new Date() - (new Date(dateIsoFormat));
        diff = Math.floor(diff / 60000);
        if (diff < 1) return 'less than a minute';
        if (diff < 60) return diff + ' minute' + pluralize(diff);
        diff = Math.floor(diff / 60);
        if (diff < 24) return diff + ' hour' + pluralize(diff);
        diff = Math.floor(diff / 24);
        if (diff < 30) return diff + ' day' + pluralize(diff);
        diff = Math.floor(diff / 30);
        if (diff < 12) return diff + ' month' + pluralize(diff);
        diff = Math.floor(diff / 12);
        return diff + ' year' + pluralize(diff);

        function pluralize(value) {
            if (value !== 1) return 's';
            else return '';
        }
    }


    render() {
        return (
            <main>
                <div className="detailed">
                    <div className="wp-content">
                        <h1>{this.state.title}</h1>

                        <div className="details-image" style={{backgroundImage: "url(" + `${this.state.image}` + ")"}}>
                        </div>

                        <div className="responsive-details">
                            <p className="details-p-left">
                                <span>{this.state.creator}</span> in {this.state.category}&ensp;- {this.calcTime(this.state.lmt)} ago</p>
                            <p className="details-p-right">{this.state.counter} views</p>

                            <h3>Description</h3>
                            <div className="description">
                                <p>{this.state.description}</p>
                            </div>
                        </div>


                    </div>
                    <br/>


                    <div className="responsive-details">

                        {/* PROPERTIES */}
                        <div className="properties">

                            <button className="btn btn--default shiny btn-download"><a href={this.state.image}
                                                                                       download>Download</a></button>
                            {this.state.creator === localStorage.getItem('username') ? <span>
                                    <button className="btn btn--default shiny btn-edit">Edit</button>
                                    <button onClick={()=>{this.deletePostById(this.props.match.params.id)}} className="btn btn--default shiny btn-delete">Delete</button>
                                </span> : <span/>}

                        </div>
                        <hr/>

                        {/*COMMENT SECTION*/}
                        <div className="comments-section">
                            <h2>Comments</h2>

                            <form onSubmit={this.onSubmitHandler} className="submit" ref="form">
                                <textarea onChange={this.onChangeHandler} name="commentText" className="text-area"
                                          cols="50" rows="5"/>
                                <button type="submit" className="btn btn--default shiny btn-edit">Submit</button>
                            </form>

                            {this.state.comments.map((comment, index) => {
                                return (
                                    <span key={index}>
                                        <div className="comment">
                                        <span>
                                           {comment.username === localStorage.getItem('username') ?
                                               <span onClick={()=>{this.deleteCmt(comment._id)}} className="hiks">delete</span> : <span/>}
                                        </span>
                                        <p className="uploaded-by"><img src={comment.userAvatar} alt="rizz"/><span className="commentator">{comment.username}</span>&ensp;{this.calcTime(comment._kmd.lmt)} ago</p>
                                        <p>{comment.comment}</p>
                                        </div>
                                    </span>
                                )
                            })}

                            {this.state.comments.length === 0 ? <p>No comments yet.</p> : <span/>}

                        </div>

                    </div>
                </div>
            </main>
        );
    }
}

export default withRouter(Details)

// Angular2 Fundamentals/Gallery-Angular2/bull-gallery/src/app/components/details/details.component.ts
import {Component, OnInit} from '@angular/core';
import {RemoteService} from "../../services/remote/remote.service";
import {ActivatedRoute, Route, Router} from "@angular/router";
import {CommentModel} from "../../services/models/comment.model";
import {FormsModule} from "@angular/forms";
import { Image, Action, ImageModalEvent, Description } from 'angular-modal-gallery';


@Component({
  selector: 'bull-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.scss']
})
export class DetailsComponent implements OnInit {
  public title: string;
  public model: CommentModel;
  public article: any;
  public image: any;
  public counter = 0;
  public username: any;
  public comment: any;
  public role: any;
  public postId: any;
  public commentFail: boolean;
  public arr = [];

  constructor(private remoteService: RemoteService, private route: ActivatedRoute, private router: Router) {
    this.username = localStorage.getItem('username');
    this.model = new CommentModel(localStorage.getItem('username'), '', '')
  }


  ngOnInit() {
    this.postId = this.route.snapshot.paramMap.get('id');


    // GET POST DETAILS
    this.remoteService.postDetails(this.postId).subscribe(data => {
        this.article = data;

      },
      err => {
        this.router.navigate([`/**`]);
      });

    // GET USER DETAILS
    this.remoteService.getUserDetails().subscribe(data => {
        this.role = data[0]['role'];
      },
      err => {
        console.log(err.message);
      });

    this.getAllComments();


  }

  // CREATE COMMENT SUBMIT
  submit() {
    this.model.username = this.username;
    this.model.postId = this.postId;

    this.remoteService.createComment(this.model).subscribe(data => {
        this.getAllComments();
        this.successfulComment();
        this.model.comment = '';

      },
      err => {
        console.log(err.message);
      })
  }

  successfulComment(): void {
    this.router.navigate([`/details/${this.postId}`]);
  }

  // GET ALL COMMENTS
  getAllComments() {

    this.remoteService.getAllComments(this.postId).subscribe(data => {
        this.arr = [];
        this.comment = data[0]['comment'];
        for (let obj in data) {
          this.arr.push(data[obj]);
        }
      },

      err => {
        console.log(err.message);
      });
  }

  // DELETE COMMENT
  deleteComment(id) {
    this.remoteService.deleteComment(id).subscribe(data => {
        this.router.navigate([`/details/${this.postId}`]);
        this.getAllComments();
      },
      err => {
        console.log(err.message);
      });
  }


  // DELETE POST
  deletePost() {
    const id = this.route.snapshot.paramMap.get('id');

    this.remoteService.deletePost(id).subscribe(data => {
        this.article = data;
        this.router.navigate(['/'])
      },
      err => {
        console.log(err.message);
      });
  }

  // NAVIGATE TO EDIT PAGE OF CLICKED POST
  editPostNavigate() {
    this.router.navigate(['/edit/' + this.route.snapshot.paramMap.get('id')])
  }


  isAdmin() {
    if (this.role === 'admin') {
      return true
    }
    return false
  }

  countClicks(e) {
    this.counter++;
  }

  calcTime(dateIsoFormat) {

    let diff = +new Date - (+new Date(dateIsoFormat));
    diff = Math.floor(diff / 60000);
    if (diff < 1) return 'less than a minute';
    if (diff < 60) return diff + ' minute' + pluralize(diff);
    diff = Math.floor(diff / 60);
    if (diff < 24) return diff + ' hour' + pluralize(diff);
    diff = Math.floor(diff / 24);
    if (diff < 30) return diff + ' day' + pluralize(diff);
    diff = Math.floor(diff / 30);
    if (diff < 12) return diff + ' month' + pluralize(diff);
    diff = Math.floor(diff / 12);
    return diff + ' year' + pluralize(diff);

    function pluralize(value) {
      if (value !== 1) return 's';
      else return '';
    }
  }


}

<main>
  <div class="detailed">
    <div class="wp-content">
      <h1>{{article?.title}}</h1>

      <div class="details-image"  [ngStyle]="{'background-image': 'url(' + article?.image + ')'} ">
        <!--<img [src]="article?.image" alt="Loading...">-->
      </div>

      <div class="responsive-details">
        <p class="details-p-left">{{calcTime(article?._kmd['lmt'])}} ago by <span>{{article?.creator}}</span> in
          {{article?.category}}</p>
        <p class="details-p-right">{{article?.counter}} views</p>

        <h3>Description</h3>
        <div class="description">
          <p>{{article?.description}}</p>
        </div>
      </div>

      <modal-gallery [modalImages]="article.image"></modal-gallery>

    </div>
    <br>

    <div class="responsive-details">
      <div class="properties">
        <!--<h2>Properties</h2>-->

        <button class="btn btn--default shiny btn-download"><a href="{{article?.image}}" download>Download</a></button>
        <span *ngIf="article?.creator == username || isAdmin()">
          <button (click)="editPostNavigate()" class="btn btn--default shiny btn-edit">Edit</button>
          <button (click)="deletePost()" class="btn btn--default shiny btn-delete">Delete</button>
        </span>
      </div>
      <hr>

      <!--COMMENT SECTION-->
      <div class="comments-section">
        <h2>Comments</h2>

        <p *ngIf="commentFail">Enter comment</p>
        <div class="submit">
          <textarea [(ngModel)]="model.comment" name="comment" class="text-area" cols="50" rows="5"></textarea>
          <button (click)="submit()" type="submit" class="btn btn--default shiny btn-edit">Submit</button>
        </div>

        <span *ngIf="arr">
          <div *ngFor="let comment of arr" class="comment">
            <span *ngIf="comment.username === username || isAdmin()"><span class="hiks"
                                                                           (click)="deleteComment(comment._id)">x</span></span>
            <p class="uploaded-by">{{calcTime(comment._kmd.lmt)}} by {{comment.username}}</p>
            <p>{{comment.comment}}</p>
          </div>
        </span>
        <p *ngIf="arr.length === 0">No comments yet.</p>


      </div>

    </div>

  </div>
</main>

<!--<textarea (input)="textValue = $event.target.value"  class="text-area" name="commentArea" cols="50" rows="5"></textarea>-->
