// Angular2 Fundamentals/Gallery-Angular2/bull-gallery/src/app/components/auth/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";

import {RemoteService} from '../../../services/remote/remote.service'
import {LoginModel} from "../../../services/models/login.model";
import {Router} from "@angular/router";

@Component({
  selector: 'bull-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  public login: FormGroup;
  public model: LoginModel;
  public loginFail:boolean;

  constructor(private router: Router, private fb: FormBuilder, private remoteService: RemoteService) {
    this.model = new LoginModel('', '')
  }

  ngOnInit() {
    this.login = this.fb.group({
      username: ['', [Validators.required, Validators.minLength(4), Validators.maxLength(12)]],
      password: ['', [Validators.required, Validators.minLength(4), Validators.maxLength(25)]]
    })
  }

  // SUBMIT LOGIN FORM
  submit(): void {
    this.model.username = this.login.value['username'];
    this.model.password = this.login.value['password'];

    this.remoteService.login(this.model)
      .subscribe(
        data => {

           this.successfulLogin(data);
        },
        err => {
          this.loginFail = true;
        }
      )
  }


  successfulLogin(data): void {
    this.remoteService.loggedIn();
    localStorage.setItem('authtoken', data['_kmd']['authtoken']);
    localStorage.setItem('username', data['username']);
    this.loginFail = false;
    this.router.navigate(['/']);
    window.location.reload();
  }

}

<div class="login-page">
  <div class="form">
    <div class="row header">
      <div class="large-12 columns">LOGIN</div>
    </div>
    <div *ngIf="loginFail" class="shiny btn-delete" style="margin-top: 20px;">Login Failed!</div>
    <form class="login-form" (ngSubmit)="submit()" [formGroup]="login">
      <input type="text" placeholder="Username" formControlName="username" />
      <input type="password" placeholder="Password" formControlName="password" />
      <button type="submit" class="btn btn--default shiny btn-login">login</button>
      <p class="message">Not registered? <a routerLink="/register">Create an account</a></p>
    </form>

  </div>

</div>

// ReactJS Fundamentals/Bull-Gallery/src/components/non-shared/Auth/Login.jsx
import React, {Component} from 'react';
import {withRouter, NavLink} from 'react-router-dom';
import {login} from '../../../api/remote';
import toastr from 'toastr';

class Login extends Component {
    constructor(props) {
        super(props);

        this.state = {
            username: '',
            password: '',
            loginFail: false
        };


        this.onChangeHandler = this.onChangeHandler.bind(this);
        this.onSubmitHandler = this.onSubmitHandler.bind(this);
    }

    onChangeHandler(e) {
        this.setState({[e.target.name]: e.target.value});
    }

    async onSubmitHandler(e) {
        e.preventDefault();

        if (this.state.username === '' || this.state.password === '') {
            toastr.error('All fields must be filled');
            return;
        }

        const res = await login(this.state.username, this.state.password);

        if (res.error) {
            toastr.error('Invalid Credentials', 'Error');
            this.state.loginFail = true;
            return;
        }

        localStorage.setItem('token', res._kmd.authtoken);
        localStorage.setItem('username', res.username);
        toastr.success('Login Successful');

        window.location.reload();
        this.props.history.push(`/`);
    }

    render() {
        return (
            <div className="login-page">
                <div className="form">
                    <div className="row header">
                        <div className="large-12 columns">LOGIN</div>
                    </div>
                    {this.state.loginFail && <div className="shiny btn-delete error">Please enter a valid username or password</div>}
                    <form onSubmit={this.onSubmitHandler} className="login-form">
                        <input onChange={this.onChangeHandler} name="username" type="text" placeholder="Username"/>
                        <input onChange={this.onChangeHandler} name="password" type="password" placeholder="Password"/>

                        <button type="submit" className="btn btn--default shiny btn-login">login</button>
                        <p className="message">Not registered? <NavLink to={'/register'}>Create an account</NavLink></p>
                    </form>
                </div>
            </div>


        );
    }
}


export default withRouter(Login)
