// Angular2 Fundamentals/Gallery-Angular2/bull-gallery/src/app/components/auth/register/register.component.ts
import {Component, OnInit} from '@angular/core';
import {AbstractControl, FormBuilder, FormGroup, Validators} from "@angular/forms";
import {Form} from '@angular/forms/src/directives/form_interface'
import {RemoteService} from '../../../services/remote/remote.service'
import {RegisterModel} from "../../../services/models/register.model";
import {Router} from "@angular/router";
import {PasswordValidation} from './validatePassword'


@Component({
  selector: 'bull-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  public register: FormGroup;
  public model: RegisterModel;
  public registerFail: boolean;
  public userN: any;
  public passW: any;
  public confirmP: any;

  constructor(private router: Router, private fb: FormBuilder, private remoteService: RemoteService) {
    this.model = new RegisterModel('', '', 'user', 'http://s3.amazonaws.com/37assets/svn/765-default-avatar.png')
  }

  ngOnInit() {
    // FORM GROUP REGISTER
    this.register = this.fb.group({
      username: ['', [Validators.required, Validators.minLength(4), Validators.maxLength(12)]],
      auth: this.fb.group({
        password: ['', [Validators.required, Validators.minLength(4), Validators.maxLength(25)]],
        confirmPassword: ['', [Validators.required, Validators.minLength(4), Validators.maxLength(25)]],
      }, {
        validator: PasswordValidation.MatchPassword
      })
    })
  }

  // SUBMIT REGISTER MODEL
  submit() {
    this.model.username = this.register.value['username'];
    this.model.password = this.register.value.auth['password'];

    //NOTIFICATIONS
    if(this.model.username === ''){
      this.userN = true;
      return
    }
    else if(this.model.password === ''){
      this.userN = false;
      this.passW = true;
      return
    }
    else if(this.register.value.auth['password'] !== this.register.value.auth['confirmPassword']){
      this.passW = false;
      this.confirmP = true;
      return
    }

    // POST REGISTER
    this.remoteService.register(this.model).subscribe(data => {
        this.successfulRegister();
        this.router.navigate(['/login']);
      },
      err => {
        console.log(err.message);
        this.registerFail = true;
      })
  }



  successfulRegister(): void {
    this.registerFail = false;
    this.router.navigate(['/']);
  }
}

<div class="login-page">
  <div class="form">
    <div class="row header">
      <div class="large-12 columns">SIGN UP</div>
    </div>

    <!--NOTIFICATION-->
    <div *ngIf="userN" class="shiny btn-delete" style="margin-top: 20px;">Please fill the username field!</div>
    <div *ngIf="passW" class="shiny btn-delete" style="margin-top: 20px;">Please fill the password field!</div>
    <div *ngIf="confirmP" class="shiny btn-delete" style="margin-top: 20px;">Passwords do not match!</div>


    <form class="login-form" (ngSubmit)="submit()" [formGroup]="register">
      <input type="text" placeholder="Username" formControlName="username" name="username"/>
      <span formGroupName="auth">
      <input type="password" placeholder="Password" formControlName="password" name="password"/>
      <input type="password" placeholder="Confirm Password" formControlName="confirmPassword" name="confirmPassword"/>
      </span>
      <button class="btn btn--default shiny btn-login" type="submit">Register</button>
      <p class="message">Already have an account? <a routerLink="/login">Login</a></p>
    </form>
  </div>
</div>

// ReactJS Fundamentals/Bull-Gallery/src/components/non-shared/Auth/Register.jsx
import React, {Component} from 'react';
import {NavLink, withRouter} from 'react-router-dom';
import toastr from 'toastr';
import {login, register} from '../../../api/remote';

class RegisterPage extends Component {
    constructor(props) {
        super(props);

        this.state = {
            username: '',
            email: '',
            password: '',
            repeat: ''
        };

        this.onChangeHandler = this.onChangeHandler.bind(this);
        this.onSubmitHandler = this.onSubmitHandler.bind(this);
    }

    onChangeHandler(e) {
        this.setState({ [e.target.name]: e.target.value });
    }

    async onSubmitHandler(e) {
        e.preventDefault();

        if (this.state.username === '' || this.state.email === '' || this.state.password === '' || this.state.repeat === '') {
            toastr.error('All fields must be filled');
            return;
        }

        if (this.state.username.length < 4 || this.state.password.length < 4) {
            toastr.error('Username and password should be at least 4 symbols');
            return;
        }

        if (this.state.password !== this.state.repeat) {
            toastr.error('Passwords do not match');
            return;
        }

        // REGISTER REQUEST
        const res = await register(this.state.username, this.state.password, 'user', "http://s3.amazonaws.com/37assets/svn/765-default-avatar.png");

        if (res.error) {
            toastr.error('Registration unsuccessful');
            return;
        }

        toastr.success('Register Successful');


        // LOGIN REQUEST
        const resLogin = await login(this.state.username, this.state.password);
        localStorage.setItem('token', resLogin._kmd.authtoken);
        localStorage.setItem('username', resLogin.username);

        this.props.history.push('/');
    }
    render() {
        return (
            <div className="login-page">
                <div className="form">
                    <div className="row header">
                        <div className="large-12 columns">Register</div>
                    </div>
                    {/*{this.state.loginFail && <div className="shiny btn-delete error">Please enter a valid username or password</div>}*/}
                    <form onSubmit={this.onSubmitHandler} className="login-form">
                        <input onChange={this.onChangeHandler} name="username" type="text" placeholder="Username"/>
                        <input onChange={this.onChangeHandler} name="email" type="email" placeholder="Email"/>
                        <input onChange={this.onChangeHandler} name="password" type="password" placeholder="Password"/>
                        <input onChange={this.onChangeHandler} name="repeat" type="password" placeholder="Repeat Password"/>

                        <button type="submit" className="btn btn--default shiny btn-login">Register</button>
                        <p className="message">Already have an account? <NavLink to={'/login'}>Sign In</NavLink></p>
                    </form>
                </div>
            </div>
        );
    }
}

export default withRouter(RegisterPage);
