// ReactJS Fundamentals/Bull-Gallery/src/components/non-shared/Edit/EditPost.jsx
import React, {Component} from 'react';
import {withRouter} from 'react-router-dom';
import toastr from 'toastr';
import {editPost, getCategories, getPostDetails, postUpload} from '../../../api/remote';

class EditPost extends Component {
    constructor(props) {
        super(props);

        this.state = {
            categories: [],
            title: '',
            image: '',
            category: '',
            description: '',
            creator: '',
            counter: 0,
            time: '',

            uploadFail: false,
            titleFail: false,
            imageFail: false,
            categoryFail: false,
            descriptionFail: false,
        };

        this.onChangeHandler = this.onChangeHandler.bind(this);
        this.onSubmitHandler = this.onSubmitHandler.bind(this);
    }

    onChangeHandler(e) {
        this.setState({[e.target.name]: e.target.value});
    }

    async componentDidMount() {


        // GET POST DETAILS
        const res = await getPostDetails(this.props.match.params.id);
        this.setState({
            title: res.title,
            image: res.image,
            category: res.category,
            description: res.description,
            creator: res.creator,
            counter: res.counter,
            time: res._kmd
        });

        // CHECK IF TRIES TO EDIT URL AND NOT CREATOR
        if(localStorage.getItem('username') !== this.state.creator){
            this.props.history.push('/');
            return
        }

        if (res.error) {
            toastr.error('Loading unsuccessful');
            return;
        }

        this.setState({
            title: res.title,
            image: res.image,
            category: res.category,
            description: res.description,
            creator: res.creator,
            counter: res.counter,
            lmt: res._kmd.lmt,
        });
        this.setState({username: localStorage.getItem('username')});


        // GETTING CATEGORIES AND PUSHING THEM INTO ARRAY
        let arrCategories = [];
        const resCategories = await getCategories();

        for (let obj in resCategories) {
            arrCategories.push(resCategories[obj]['category']);
        }
        this.setState({categories: arrCategories});
    }

    async onSubmitHandler(e) {
        e.preventDefault();

        // FORM ERROR HANDLING
        if (this.state.title === '' && this.state.image === '' && this.state.category === '' && this.state.description === '') {
            this.setState({
                uploadFail: true,
                titleFail: false,
                imageFail: false,
                categoryFail: false,
                descriptionFail: false
            });
            return;
        }

        if (this.state.title === '') {
            this.setState({
                uploadFail: false,
                titleFail: true,
                imageFail: false,
                categoryFail: false,
                descriptionFail: false
            });
            return;
        }

        if (this.state.image === '') {
            this.setState({
                uploadFail: false,
                titleFail: false,
                imageFail: true,
                categoryFail: false,
                descriptionFail: false
            });
            return;
        }

        if (this.state.category === '') {
            this.setState({
                uploadFail: false,
                titleFail: false,
                imageFail: false,
                categoryFail: true,
                descriptionFail: false
            });
            return;
        }

        if (this.state.description === '') {
            this.setState({
                uploadFail: false,
                titleFail: false,
                imageFail: false,
                categoryFail: false,
                descriptionFail: true
            });
            return;
        }

        //TODO ERROR INVALID CATEGORY

        // PUT REQUEST
        const res = await editPost(
            this.props.match.params.id,
            this.state.title,
            this.state.image,
            this.state.category,
            this.state.description,
            this.state.creator,
            this.state.counter,
            this.state.time
        );
        if (res.success) {
            toastr.success('Post Updated Successfully')
        }
        this.props.history.push(`/details/${this.props.match.params.id}`);
    }


    render() {
        return (

            <div className="login-page">
                <div className="form  upload-form">
                    <div className="row header">
                        <div className="large-12 columns">Edit Post</div>
                    </div>

                    {this.state.uploadFail ?
                        <div className="shiny btn-delete form-error">All fields must be filled !</div> : <span/>}
                    {this.state.titleFail ? <div className="shiny btn-delete form-error">Title must be filled !</div> :
                        <span/>}
                    {this.state.imageFail ? <div className="shiny btn-delete form-error">Image must be filled !</div> :
                        <span/>}
                    {this.state.categoryFail ?
                        <div className="shiny btn-delete form-error">Please choose a category !</div> : <span/>}
                    {this.state.descriptionFail ?
                        <div className="shiny btn-delete form-error">Description must be filled !</div> : <span/>}

                    <form onSubmit={this.onSubmitHandler} className="login-form">
                        <label htmlFor="title">Title</label>
                        <input onChange={this.onChangeHandler} name="title" id="title" type="text" placeholder="Title"
                               value={this.state.title}/>

                        <label htmlFor="image">Image</label>
                        <input onChange={this.onChangeHandler} name="image" id="image" type="text" placeholder="Image"
                               value={this.state.image}/>

                        <label htmlFor="select">Category</label>
                        <select onChange={this.onChangeHandler} name="category" id="select">
                            <option value="category" className="option" disabled
                                    selected="selected">{this.state.category}</option>
                            {this.state.categories.map((category, index) => {
                                return (
                                    <option key={index}>{category}</option>
                                )
                            })}
                        </select>

                        <label htmlFor="description">Description</label>
                        <textarea onChange={this.onChangeHandler} className="textarea-upload" id="description"
                                  name="description" placeholder="Description" value={this.state.description}/>

                        <button className="btn btn--default shiny btn-login" type="submit">Submit</button>
                    </form>
                </div>
            </div>


        );
    }
}

export default withRouter(EditPost);

// Angular2 Fundamentals/Gallery-Angular2/bull-gallery/src/app/components/edit-post/edit-post.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";

import {RemoteService} from '../../services/remote/remote.service'
import {UploadModel} from "../../services/models/upload.model";
import {ActivatedRoute, Router} from "@angular/router";

@Component({
  selector: 'bull-edit-post',
  templateUrl: './edit-post.component.html',
  styleUrls: ['./edit-post.component.scss']
})
export class EditPostComponent implements OnInit {

  public editPostGroup: FormGroup;
  public model: UploadModel;
  public uploadFail: boolean;
  public titleFail: boolean;
  public imageFail: boolean;
  public categoryFail: boolean;
  public descriptionFail: boolean;
  public validCategory: boolean = false;
  public ifNotValid: boolean;
  public category: any;
  public categoriesArr: any;
  public article: any;
  public id: any;

  constructor(private router: Router, private fb: FormBuilder, private remoteService: RemoteService, private route: ActivatedRoute) {
    this.model = new UploadModel('', '', '', '', localStorage.getItem('username'), 0);
  }

  ngOnInit() {
    let arr = [];

    this.id = this.route.snapshot.paramMap.get('id');

    this.editPostGroup = this.fb.group({
      title: [''],
      image: [''],
      category: [''],
      description: ['']
    });


    // GET POST DETAILS
    this.remoteService.postDetails(this.id).subscribe(data => {
        this.article = data;

        this.editPostGroup = this.fb.group({
          title: [data['title']],
          image: [data['image']],
          category: [data['category']],
          description: [data['description']]
        });
      },
      err => {
        console.log(err.message);
      });


    // GET ALL CATEGORIES FROM COLLECTION
    this.remoteService.getCategories().subscribe((data) => {
        for (let obj in data) {
          arr.push(data[obj]['category']);
        }
      },
      err => {
        console.log(err.message);
      });

    this.categoriesArr = arr;

  }

  onChange(category) {
    this.category = category;

  }


  // TO SAVE CHANGES FROM EDIT POST
  submit() {
    this.model.title = this.editPostGroup.value['title'];
    this.model.image = this.editPostGroup.value['image'];
    this.model.category = this.category;
    this.model.description = this.editPostGroup.value['description'];


    //NOTIFICATIONS
    if (this.model.title === '') {
      this.titleFail = true;
      return
    }
    else if (this.model.image === '') {
      this.titleFail = false;
      this.imageFail = true;
      return
    }
    else if (this.category === '' || this.category === null || this.category === undefined) {
      this.imageFail = false;
      this.categoryFail = true;
      return
    }
    else if (this.model.description === '') {
      this.categoryFail = false;
      this.descriptionFail = true;
      return
    }


    // IF USER TRIES MANUALLY TO ADD CATEGORY FROM HTML
    this.categoriesArr.map(data => {
      if (data == this.model.category) {
        this.validCategory = true;
      }
    });

    if (!this.validCategory) {
      this.ifNotValid = true;
      return
    }
    /////////////////////////////


    // PUT EDIT POST
    this.remoteService.editPost(this.model, this.id).subscribe(data => {

        this.successfulEditPost();
      },
      err => {
        console.log(err.message);
        this.uploadFail = true;
      })
  }

  successfulEditPost(): void {
    this.categoriesArr.push(this.category);

    this.uploadFail = false;
    this.router.navigate(['/']);
  }


}

<div class="login-page">
  <div class="form  upload-form">
    <div class="row header">
      <div class="large-12 columns">EDIT POST</div>
    </div>

    <!--NOTIFICATION-->
    <div *ngIf="titleFail" class="shiny btn-delete" style="margin-top: 20px;">Please fill title field!</div>
    <div *ngIf="imageFail" class="shiny btn-delete" style="margin-top: 20px;">Please fill image field!</div>
    <div *ngIf="categoryFail" class="shiny btn-delete" style="margin-top: 20px;">Please choose category!</div>
    <div *ngIf="descriptionFail" class="shiny btn-delete" style="margin-top: 20px;">Please fill the description!</div>

    <span *ngIf="ifNotValid">
      <div *ngIf="!validCategory" class="shiny btn-delete" style="margin-top: 20px;">Please choose a valid category!</div>
    </span>

    <form class="login-form" (ngSubmit)="submit()" [formGroup]="editPostGroup">
      <label for="title">Title</label>
      <input formControlName="title" id="title" type="text" placeholder="Title"/>

      <label for="image">Image</label>
      <input formControlName="image" id="image" type="text" placeholder="Image"/>

      <label for="select">Category</label>
      <select (change)="onChange($event.target.value)" name="category" id="select">
        <option value="category" class="option" disabled selected>choose a category</option>
        <option value={{category}} *ngFor="let category of categoriesArr">{{category}}</option>
      </select>


      <label for="description">Description</label>
      <textarea formControlName="description" id="description" placeholder="Description"></textarea>


      <button class="btn btn--default shiny btn-login" type="submit">Save</button>
    </form>
  </div>
</div>
