// ReactJS Fundamentals/Bull-Gallery/src/components/shared/common/Header.jsx
import React, {Component} from 'react';
import {withRouter, NavLink, Link} from 'react-router-dom';
import logo from './images/logo.png'
import * as $ from 'jquery';
import {getUserDetails, getCategories} from "../../../api/remote";

class Header extends Component {
    constructor(props) {
        super(props);

        this.state = {
            avatar: '',
            categories: []
        };

        this.dropdownProfile = this.dropdownProfile.bind(this);
        this.dropdownMobileMenu = this.dropdownMobileMenu.bind(this);
    }


    dropdownProfile() {
        $('.dropdown2').next('.dropdown-content2').slideToggle('fast');
    }

    dropdownMobileMenu() {
        $('#nav-icon4').toggleClass('open');
        $('#nav-icon4').next('.mobile-menu').slideToggle('fast');

    }

    async componentDidMount() {

        if (localStorage.getItem('username')) {
            // GETTING USER DETAILS
            const res = await getUserDetails();
            this.state.avatar = res[0].avatar;
            this.setState({avatar: res[0].avatar});

            // GETTING CATEGORIES AND PUSHING THEM INTO ARRAY
            let arrCategories = [];
            const resCategories = await getCategories();

            for (let obj in resCategories) {
                arrCategories.push(resCategories[obj]['category']);
            }
            this.setState({categories: arrCategories});
        }

    }

    render() {

        return (
            <header>
                <nav>

                    <ul className="nav-bar">
                        <li className="left">
                            <img className="logo" src={logo} alt="logo"/>
                        </li>
                        <li className="left"><NavLink to={'/'}>Home</NavLink></li>
                        <li className="left">
                            <NavLink to={`/categories`} className="dropdown">Categories</NavLink>
                            {/*<div className="dropdown-content">*/}
                                {/*{this.state.categories.map((category, index) => {*/}
                                    {/*return (*/}
                                        {/*<Link to={`/categories`}*/}
                                              {/*key={index}><span>{category}</span></Link>*/}
                                    {/*)*/}
                                {/*})}*/}

                            {/*</div>*/}
                        </li>


                        {this.props.loggedIn() &&
                        <li className="right" onClick={this.dropdownProfile}>
                            <img className="avatar dropdown2" src={this.state.avatar} alt="avt"/>
                        </li>}
                        {this.props.loggedIn() &&
                        <li className="right" onClick={this.dropdownProfile}>
                            <a className="dropdown2">{localStorage.getItem('username')}</a>
                            {/*PROFILE DROPDOWN*/}
                            <div className="dropdown-content dropdown-content2">
                                <NavLink to={`/profile/${localStorage.getItem('username')}`}>Profile</NavLink>
                                <a href="javascript:void(0)" onClick={this.props.onLogout}>Logout</a>
                            </div>
                        </li>}

                        {!this.props.loggedIn() && <li className="right"><NavLink to={'/login'}>Login</NavLink></li>}
                        {!this.props.loggedIn() &&
                        <li className="right"><NavLink to={'/register'}>Register</NavLink></li>}
                        {this.props.isAdmin() && <li className="right"><NavLink to={'/admin'}>Admin</NavLink></li>}
                        <li className="right upload shiny"><NavLink to={'/upload'}>Upload</NavLink></li>

                    </ul>


                    {/* MOBILE MENU */}
                    <div id="nav-icon4" onClick={this.dropdownMobileMenu}>
                        <span/>
                        <span/>
                        <span/>
                    </div>

                    <ul className="mobile-menu">
                        <li><Link to={'/'}>Home</Link></li>
                        <li>
                            <Link to={`/categories`} className="mobile-dropdown">Categories</Link>
                            {/*<div className="mobile-dropdown-content">*/}
                                {/*{this.state.categories.map((category, index) => {*/}
                                    {/*return (*/}
                                        {/*<Link to={`/category/${category}`}*/}
                                                 {/*key={index}><span>{category}</span></Link>*/}
                                    {/*)*/}
                                {/*})}*/}
                            {/*</div>*/}
                        </li>

                        {!this.props.loggedIn() && <li><Link to={'/login'}>Login</Link></li>}
                        {!this.props.loggedIn() && <li><Link to={'/register'}>Register</Link></li>}
                        {this.props.loggedIn() && <li><Link to={'/admin'}>Admin</Link></li>}
                        {this.props.loggedIn() &&
                        <li><Link to={'/profile'}>{localStorage.getItem('username')}</Link></li>}
                        {this.props.loggedIn() &&
                        <li><a href="javascript:void(0)" onClick={this.props.onLogout}>Logout</a></li>}
                        {this.props.loggedIn() && <li className="shiny"><Link to={'/upload'}>Upload</Link></li>}

                    </ul>
                    <Link className="mobile-logo" to={'/'}><h2>Bull Gallery</h2></Link>
                </nav>


            </header>
        );
    }
}

export default withRouter(Header)

// Angular2 Fundamentals/Gallery-Angular2/bull-gallery/src/app/components/common/header/header.component.ts
import {Component, OnInit, DoCheck} from '@angular/core';
import * as $ from 'jquery';

import {Router, RouterModule, RouterLink} from '@angular/router';
import {RemoteService} from "../../../services/remote/remote.service";

@Component({
  selector: 'bull-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  public username: string;
  public avatar: string;
  public categoriesArr: any;
  public role: string;


  constructor(public remoteService: RemoteService, private router: Router) {
    this.username = localStorage.getItem('username');

  }


  ngOnInit() {
    this.dropdown();
    let arr = [];

    // GET USER DETAILS
    this.remoteService.getUserDetails().subscribe(data => {
        this.avatar = data[0]['avatar'];
        this.role = data[0]['role'];
      },
      err => {
        console.log(err.message);
      });

    // GET ALL CATEGORIES
    this.remoteService.getCategories().subscribe((data) => {
        for (let obj in data) {
          arr.push(data[obj]['category']);
        }

      },
      err => {
        console.log(err.message);
      });

    this.categoriesArr = arr;
  }



  // NAVIGATE TO CATEGORY URL
  clickCategory(categ) {
    this.remoteService.listAllPostsFromCategory(categ).subscribe(data => {

        this.router.navigate([`/category/${categ}`]);
        window.location.reload();
      },
      err => {
        console.log(err.message);
      });
     }

  private dropdown() {
    $('.dropdown').click(function (e) {
      e.preventDefault();
      $(this).next('.dropdown-content').slideToggle('fast');
    });

    $('.mobile-dropdown').click(function (e) {
      e.preventDefault();
      $(this).next('.mobile-dropdown-content').slideToggle('fast');
    });


    $('#nav-icon4').click(function () {
      $(this).toggleClass('open');
      $('.mobile-menu').slideToggle();
    });
  }

  dropdown2(e) {
    e.preventDefault();
    $('.dropdown2').next('.dropdown-content2').slideToggle('fast');


  }


  loggedIn() {
    return !!localStorage.getItem('authtoken');
  }

  isAdmin() {
    if (this.role === 'admin') {
      return true
    }
    return false
  }

  logout() {
    this.remoteService.logout().subscribe(data => {
      localStorage.clear();
      this.router.navigate(['/login']);
      // window.location.reload();
    });

  }
}

<nav>
  <ul class="nav-bar">
    <li class="left"><img routerLink="/" class="avatar" src="../../../../assets/images/bull-logo.png"
                          style="margin: 0 10px 20px 0 ; width: 60px;"/></li>
    <li class="left"><a class="active" routerLink="/">Home</a></li>
    <li class="left">
      <a  class="dropdown">Categories</a>
      <div class="dropdown-content">
        <a *ngFor="let category of categoriesArr" (click)="clickCategory(category)" >{{category}}</a>
      </div>
    </li>


    <li *ngIf="loggedIn()" class="right"><img (click)="dropdown2($event)" class="avatar dropdown2" src={{avatar}}></li>
    <li *ngIf="loggedIn()" class="right"><a (click)="dropdown2($event)" class="dropdown2">{{username}}</a>
      <!--OPTIONAL DROPDOWN-->
      <div class="dropdown-content dropdown-content2">
        <a routerLink="/profile">Profile</a>
        <a (click)="logout()">Logout</a>
      </div>
    </li>
    <!--<li *ngIf="loggedIn()" class="right"><a (click)="logout()">Logout</a></li>-->
    <li *ngIf="!loggedIn()" class="right"><a routerLink="/login">Login</a></li>
    <li *ngIf="!loggedIn()" class="right"><a routerLink="/register">Register</a></li>
    <li *ngIf="isAdmin() && loggedIn()"  class="right"><a routerLink="/admin">Admin</a></li>

    <li class="right upload shiny"><a routerLink="/upload">Upload</a></li>
  </ul>


  <div id="nav-icon4">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <ul class="mobile-menu">
    <li><a routerLink="/">Home</a></li>
    <li>
      <a class="mobile-dropdown">Categories</a>
      <div class="mobile-dropdown-content">
        <a *ngFor="let category of categoriesArr" (click)="clickCategory(category)">{{category}}</a>
      </div>
    </li>
    <li *ngIf="loggedIn()"><a (click)="logout()">Logout</a></li>
    <li *ngIf="!loggedIn()"><a routerLink="/login">Login</a></li>
    <li *ngIf="!loggedIn()"><a routerLink="/register">Register</a></li>
    <li *ngIf="loggedIn()"><a routerLink="/profile">{{username}}</a></li>
    <li *ngIf="isAdmin() && loggedIn()"><a routerLink="/admin">Admin</a></li>
    <li class="shiny"><a routerLink="/upload">Upload</a></li>
  </ul>

</nav>
